name: Basic Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Runs at the end of every day (midnight Amsterdam converted to UTC)

jobs:
  simple-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node modules
        run: npm ci
        env:
          CI: true

      - name: Create new booking
        env:
          REFRESH_TOKEN: ${{ secrets.DESKBIRD_REFRESH_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DESKBIRD_RESOURCE_ID: ${{ env.DESKBIRD_RESOURCE_ID }}
          DESKBIRD_ZONE_ITEM_ID: ${{ env.DESKBIRD_ZONE_ITEM_ID }}
          DESKBIRD_WORKSPACE_ID: ${{ env.DESKBIRD_WORKSPACE_ID }}
        run: npm run start
